---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: LukeParkerDev.Blog/wwwroot/posts
  label: Posts
  create: documents
  match: "*.md"
  new_doc_ext: md
upload_dir: LukeParkerDev.Blog/wwwroot/uploads
public_path: "/_content/LukeParkerDev.Blog/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:-:month:-:day:-:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
