name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        include-prerelease: true
    - name: Publish Blog BuildJob
      run: dotnet publish LukeParkerDev.Blog.BuildJob/LukeParkerDev.Blog.BuildJob.csproj -c Release -o release --nologo
    - name: Publish 
      run: dotnet publish LukeParkerDev.Web/LukeParkerDev.Web.csproj -c Release -o release --nologo
    - name: Deploy to CloudFlare Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: cf-pages
        FOLDER: release/wwwroot
    # Changes the base-tag in index.html from '/' to 'LukeParkerDev' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to LukeParkerDev
      run: sed -i 's/<base href="\/" \/>/<base href="\/LukeParkerDev\/" \/>/g' release/wwwroot/index.html
    # Add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
    - name: Clear Cloudflare Cache
      id: clearcloudflarecache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
